### PR TITLE
WP-CLI Themes: Added workaround to equalize folder naming conventions across Win/Mac/Linux

### LINKED ISSUE #121: Bug: False positive result shown when theme slug is entered in non-lowercase for activation
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Enter theme slug in non-lowercase when activating it (Examples: `wp theme activate Dara`, `wp theme 
- Notice a success message shown `Success: Switched to 'Dara' theme.`
- Enter `wp theme list` to notice that no themes are active

```
➜  local wp theme list
+-----------------+----------+--------+---------+
| name            | status   | update | version |
+-----------------+----------+--------+---------+
| dara            | inactive | none   | 1.2.1   |
| twentyseventeen | inactive | none   | 1.7     |
+-----------------+----------+--------+---------+
➜  local
```

**What is expected:** Theme activation does not go through, and the success notice is not shown.

**What happens instead:** A success message is shown, but no theme is not activated.

**Screencast indicating this behaviour:** https://asciinema.org/a/JICHDMDwcPjsVibxZMUlHOHRJ

In theory, slug is supposed to be entered in lowercase. 

-- 

- Tested on a local install of WordPress. WordPress 4.9.8
- PHP version: 7.2.8
- WP-CLI version: 2.0.0

### PR DESCRIPTION
**Pull request by beaucollins**
- Test added and commits rebased on behalf of @achyuthajoy (PR #151)
- Fixes #121
- Error message when a case insensitive match exists has been improved:

```
wp theme delete P2
Error: The 'P2' theme could not be found. Did you mean 'p2'?
```
---

Modified Theme Fetcher to strict compare specified theme slug against existing ones as a Workaround to Operating System folder naming conventions.

This will equalize the non-lowercase slugs across all operating systems. If exact slug is not found, error is returned.

Fix to #121 - More info added to the bug report

--  @achyuthajoy

### CODE REVIEW

File: src/WP_CLI/Fetchers/Theme.php [hunk 1]
```diff
@@ -19,13 +19,39 @@ class Theme extends Base {
...
+	/**
+	 * Find and return the key in $existing_themes that matches $name with
+	 * a case insensitive string comparison.
+	 *
+	 * @param string $name Name of theme received by command.
+	 * @param array  $existing_themes Key/value pair of existing themes, key is
+	 *               a case sensitive name.
+	 * @return string|boolean Case sensitive name if match found, otherwise false.
+	 */
+	private function find_inexact_match( $name, $existing_themes ) {
```
Comment (schlessera) [inline src/WP_CLI/Fetchers/Theme.php]: We can integrate the suggestion algorithm in here that also accounts for typos.
First we need to add an import at the top of the file:
```php
use WP_CLI\Utils;
```

Then we can use that to also recognise words that are "close enough":
```php
private function find_inexact_match( $name, $existing_themes ) {
	$suggestion = Utils\find_suggestion(
		strtolower( $name ),
		array_keys( array_map( 'strtolower', $existing_themes ) )
	);

	if ( '' !== $suggestion ) {
		return $suggestion;
	}
	
	return false;
}
```
Now, you'll also receive suggestions with typos like:
```
Error: The 'Twentyelven' theme could not be found. Did you mean 'twentyeleven'?

File: src/WP_CLI/Fetchers/Theme.php [hunk 2]
```diff
@@ -19,13 +19,39 @@ class Theme extends Base {
...
 		return $theme;
 	}
+
+	/**
+	 * Find and return the key in $existing_themes that matches $name with
+	 * a case insensitive string comparison.
+	 *
+	 * @param string $name Name of theme received by command.
+	 * @param array  $existing_themes Key/value pair of existing themes, key is
+	 *               a case sensitive name.
```
Comment (schlessera) [inline src/WP_CLI/Fetchers/Theme.php]: Alignment is off here:
```suggestion
	 *                                a case sensitive name.
```

File: src/WP_CLI/Fetchers/Theme.php [hunk 3]
```diff
@@ -19,13 +19,39 @@ class Theme extends Base {
 	 * @return object|false
 	 */
 	public function get( $name ) {
-		$theme = wp_get_theme( $name );
-
-		if ( ! $theme->exists() ) {
+		// Workaround to equalize folder naming conventions across Win/Mac/Linux
```
Comment (schlessera) [inline src/WP_CLI/Fetchers/Theme.php]:
```suggestion
		// Workaround to equalize folder naming conventions across Win/Mac/Linux.
```

**Comment by schlessera** [comment]
Failed tests are unrelated, merging regardless.

**Comment by schlessera** [comment]
Thanks for the PR, @achyuthajoy & @beaucollins !
