### PR TITLE
Fix plugin/theme update behaviour when it has higher version than expected

### LINKED ISSUE #187: `wp plugin update --all` reports false positive update "status" when local version is higher than repo
## Bug Report
- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
Definitely Related: #142 
Maybe Related: #175

It's not all that uncommon to run a version of a plugin (or theme) that is higher than the version in the repository. In my case, I'm running one more-recent version of a plugin from Github that hasn't been released in the repo and a personal copy of a plugin with numerous bug fixes that I haven't been able to get merged.

```console
$ wp plugin update --all
The plugin is at the latest version.
The plugin is at the latest version.
+---------------------+-------------+-------------+---------+
| name                | old_version | new_version | status  |
+---------------------+-------------+-------------+---------+
| content-audit-FIXES | 2.0a        |             | Updated |
| wp-help-master      | 1.6.0-beta1 |             | Updated |
+---------------------+-------------+-------------+---------+
Success: Updated 2 of 2 plugins.
```

**Describe how other contributors can replicate this bug**

1. Bump the Version number of any plugin in the repo so it's higher than the latest version
1. `$ wp plugin update --all`
1. result name shows "Updated"

**Describe what you would expect as the correct outcome**

WP-CLI should report that the plugin version is higher than expected _and no action was taken._

**Let us know what environment you are running this on**

```
OS:     Linux 4.9.93-boot2docker #1 SMP Thu Jul 19 18:29:50 UTC 2018 x86_64
Shell:
PHP binary:     /opt/php/7.2.0/bin/php
PHP version:    7.2.0
php.ini used:   /conf/php/7.2.0/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  //wp-cli.yml
WP-CLI version: 2.2.0
```

**Provide a possible solution**

Using example from the above and taking inspiration from `$ wp plugin list`:

```console
$ wp plugin update --all
Warning: Version higher than expected.
Warning: Version higher than expected.
Error: No plugins updated.
```

### PR DESCRIPTION
**Pull request by thrijith**
Fixes #187

### CODE REVIEW

File: src/WP_CLI/CommandWithUpgrade.php [hunk 1]
```diff
@@ -16,6 +16,9 @@ abstract class CommandWithUpgrade extends \WP_CLI_Command {
 
 	protected $chained_command = false;
 
+	// Invalid version message.
+	protected $invalid_version_message = 'version higher than expected';
```
Comment (schlessera) [inline src/WP_CLI/CommandWithUpgrade.php]: This should be a protected constant instead.
```suggestion
	protected const INVALID_VERSION_MESSAGE = 'version higher than expected';
```

Comment (thrijith) [reply src/WP_CLI/CommandWithUpgrade.php]: Class constant visibility was introduced in PHP `7.1` so we can't keep it as protected, should I just update it to be a `const`?

Comment (schlessera) [reply src/WP_CLI/CommandWithUpgrade.php]: Ah, yes, you are right. Just use `const` without modifier then.

File: src/Plugin_Command.php [hunk 2]
```diff
@@ -672,7 +672,7 @@ protected function get_item_list() {
 
 				// Compare version and update information in plugin list.
 				if ( null !== $plugin_update_info && version_compare( $details['Version'], $plugin_update_info->new_version, '>' ) ) {
-					$items[ $file ]['update'] = 'version higher than expected';
+					$items[ $file ]['update'] = self::INVALID_VERSION_MESSAGE;
```
Comment (schlessera) [inline src/Plugin_Command.php]: As the class is not `final`, it's safer to use `static` here, otherwise extension can produce unexpected results...
```suggestion
					$items[ $file ]['update'] = static::INVALID_VERSION_MESSAGE;
```

File: src/Theme_Command.php [hunk 3]
```diff
@@ -480,7 +480,7 @@ protected function get_item_list() {
 
 			// Compare version and update information in theme list.
 			if ( isset( $theme_version_info[ $key ] ) && false === $theme_version_info[ $key ] ) {
-				$items[ $file ]['update'] = 'version higher than expected';
+				$items[ $file ]['update'] = self::INVALID_VERSION_MESSAGE;
```
Comment (schlessera) [inline src/Theme_Command.php]:
```suggestion
				$items[ $file ]['update'] = static::INVALID_VERSION_MESSAGE;
```

File: src/WP_CLI/CommandWithUpgrade.php [hunk 4]
```diff
@@ -354,6 +357,15 @@ protected function update_many( $args, $assoc_args ) {
 			}
 		}
 
+		// Check for items to update and remove extensions that have version higher than expected.
+		foreach ( $items_to_update as $item_key => $item_info ) {
+			if ( self::INVALID_VERSION_MESSAGE === $item_info['update'] ) {
+				WP_CLI::warning( "{$item_info['name']}: " . self::INVALID_VERSION_MESSAGE . '.' );
```
Comment (schlessera) [inline src/WP_CLI/CommandWithUpgrade.php]:
```suggestion
				WP_CLI::warning( "{$item_info['name']}: " . static::INVALID_VERSION_MESSAGE . '.' );
```

File: src/WP_CLI/CommandWithUpgrade.php [hunk 5]
```diff
@@ -354,6 +357,15 @@ protected function update_many( $args, $assoc_args ) {
 			}
 		}
 
+		// Check for items to update and remove extensions that have version higher than expected.
+		foreach ( $items_to_update as $item_key => $item_info ) {
+			if ( self::INVALID_VERSION_MESSAGE === $item_info['update'] ) {
```
Comment (schlessera) [inline src/WP_CLI/CommandWithUpgrade.php]:
```suggestion
			if ( static::INVALID_VERSION_MESSAGE === $item_info['update'] ) {
```
