### PR TITLE
Prevent array access notice when `$update_info` is null

### LINKED ISSUE #209: get_item_list has an array access issue
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Command `wp plugin list` produced this behaviour on an install (not mine, but opening the issue for them regardless).

```
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:11
PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:74
PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23
PHP   7. WP_CLI\Runner->run_command_and_exit() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1160
PHP   8. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:394
PHP   9. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:371
PHP  10. call_user_func:{phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:451}() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:451
PHP  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure:phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:95-102}() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:451
PHP  12. call_user_func:{phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:98}() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:98
PHP  13. Plugin_Command->list_() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:98
PHP  14. Plugin_Command->_list() phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php:1090
PHP  15. Plugin_Command->get_all_items() phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php:468
PHP  16. Plugin_Command->get_item_list() phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php:219
```

## Trace / reason

Code here https://github.com/wp-cli/extension-command/blob/master/src/Plugin_Command.php#L650-L663 is responsible for it.

The variable `$update_info` is going to be an array if and only if the all update info contains data for that plugin file, and that data is not null. Otherwise the value of `$update_info` is going to be null (L650).

Later though in the `$items` array the code tries to assign `$update_info['new_version']` and `package` to elements of the `$items` array which is going to produce the above notice if `$update_info` was `null`.

I haven't tested it, but I suppose this could happen if there are plugins that are custom, and are not part of the .org repository, therefore an update check wouldn't return anything about them.

**Describe what you would expect as the correct outcome**

Running `wp plugin list` with custom plugins would produce no php notices, warnings, or errors.

**Let us know what environment you are running this on**

```
PHP binary:	/usr/local/Cellar/php/7.4.2/bin/php
PHP version:	7.4.2
php.ini used:	/usr/local/etc/php/7.4/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/elliottrichmond
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```

**Provide a possible solution**

Guard against `$update_info` being `null`, or assign a more sensible default value.

### LINKED ISSUE #213: Trying to access array offset on value of type null
I'm seeing this when running `wp plugin list`:

Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in /Users/Till/.composer/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663

### PR DESCRIPTION
**Pull request by dsifford**
This PR fixes a warning that shows up in PHP 7.4 when the command attempts to access an array index on `NULL`.

See https://wordpress.slack.com/archives/C02RP4T41/p1582500876002400 for more context.

closes #209
closes #213

Ping @schlessera

### CODE REVIEW

File: src/Plugin_Command.php [hunk 1]
```diff
@@ -659,8 +659,8 @@ protected function get_item_list() {
 				'name'           => $name,
 				'status'         => $this->get_status( $file ),
 				'update'         => (bool) $update_info,
-				'update_version' => $update_info['new_version'],
-				'update_package' => $update_info['package'],
+				'update_version' => is_array( $update_info ) ? $update_info['new_version'] : null,
```
Comment (schlessera) [inline src/Plugin_Command.php]: As we're dealing with WordPress, we should take the safest route possible to make it as robust as possible.

Therefore, it's preferable to use `isset( $update_info['new_version'] )` instead of `is_array( $update_info )`, as it will also cover the case where `$update_info` is an array but does not contain the key `new_version`.

All checks should be updated to that effect.

Comment (dsifford) [reply src/Plugin_Command.php]: I assume you'd want the call to `isset` to be chained after a call to `is_array`? Otherwise, wouldn't this still trigger the warning?

Comment (dsifford) [reply src/Plugin_Command.php]: ^disregard

**Comment by schlessera** [comment]
Thanks for the PR, @dsifford !
